/**
 * Core tests: parser, assigner, and bells-used strip.
 * Run: npm test  (or: node test/core.test.mjs)
 * Requires: npm run build (or that ts-node / compiled output exists).
 * We use the compiled .vite output from `npm start` / the build step.
 */
import { readFileSync } from 'fs';

// Use Vite-built files (run `npm start` once to populate .vite/)
// Fall back to ts-node if available.
// For simplicity we compile the core files on the fly with esbuild.
import { buildSync } from 'esbuild';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { SAMPLE_EVENTS } from './fixtures/generate-sample.mjs';

const __dir = dirname(fileURLToPath(import.meta.url));
const root = join(__dir, '..');

// Bundle only the core files in-memory via esbuild
buildSync({
  entryPoints: [
    join(root, 'src/core/mscz-parser.ts'),
    join(root, 'src/core/assigner.ts'),
    join(root, 'src/core/bells-used.ts'),
  ],
  bundle: true,
  format: 'esm',
  platform: 'node',
  packages: 'external',
  outdir: join(__dir, '.build'),
  external: ['fflate', '@xmldom/xmldom'],
});

const { parseNotes, getDivision } = await import('./.build/mscz-parser.js');
const { assignPlayers, buildConflictGraph } = await import('./.build/assigner.js');
const { buildBellsUsedScore, nameToPitchTpc } = await import('./.build/bells-used.js');

const msczBytes = new Uint8Array(readFileSync(join(__dir, 'fixtures/Sample.mscz')));

// ── Parser ───────────────────────────────────────────────────────────────────
// test/fixtures/Sample.mscz is generated by test/fixtures/generate-sample.mjs,
// which also exports SAMPLE_EVENTS: the exact notes in the score, computed
// independently of the parser. The parser must reproduce them exactly.
const events = parseNotes(msczBytes);
const division = getDivision(msczBytes);

const EXPECTED_DIVISION = 480;
const EXPECTED_COUNT = 234;
// The 22 distinct bells in Sample.mscz (its A#4 is merged into the dominant Bb4).
const EXPECTED_NAMES = ['A3','A4','B4','Bb3','Bb4','C3','C4','C5','D3','D4','D5','E3','E4','E5','F#4','F3','F4','F5','G#4','G3','G4','G5'].sort();

let pass = 0, fail = 0;
function check(label, got, expected) {
  const ok = JSON.stringify(got) === JSON.stringify(expected);
  console.log(`${ok ? '✓' : '✗'} ${label}`);
  if (!ok) { console.log(`  expected: ${JSON.stringify(expected)}`); console.log(`  got:      ${JSON.stringify(got)}`); }
  ok ? pass++ : fail++;
}

check('division == 480', division, EXPECTED_DIVISION);
check(`event count == ${EXPECTED_COUNT}`, events.length, EXPECTED_COUNT);

// Same notes, same timing (incl. dotted rhythms, rests, chords, the 4/4 → 3/4 change).
const eventKey = e => `${e.name}@${e.onset}-${e.end}#${e.midi}`;
const parsedKeys = new Set(events.map(eventKey));
const oracleKeys = new Set(SAMPLE_EVENTS.map(eventKey));
check('every parsed event is in the score', [...parsedKeys].filter(k => !oracleKeys.has(k)).slice(0, 5), []);
check('every note in the score is parsed', [...oracleKeys].filter(k => !parsedKeys.has(k)).slice(0, 5), []);

const noteNames = [...new Set(events.map(e => e.name))].sort();
check('22 distinct note names', noteNames, EXPECTED_NAMES);
check('enharmonic A#4 merged into Bb4', [noteNames.includes('A#4'), noteNames.includes('Bb4')], [false, true]);

// ── Assigner ─────────────────────────────────────────────────────────────────
// At 10 players, no min-gap. Pinned to handsPerPlayer: 1 (strict independent-set
// mode) so these checks exercise the strict algorithm.
const a10 = assignPlayers(events, 10, { division, handsPerPlayer: 1 });

const allBells = events.map(e => e.name).filter((v, i, arr) => arr.indexOf(v) === i).sort();
const assignedBells = a10.players.flat().sort();
check('all bells assigned exactly once', assignedBells, allBells);

// Conflict-free check: build conflict graph, verify no player has a conflicting pair
const conflict = buildConflictGraph(events);
let conflictFree = true;
for (const bells of a10.players) {
  for (let i = 0; i < bells.length; i++) {
    for (let j = i + 1; j < bells.length; j++) {
      if (conflict[bells[i]]?.has(bells[j])) { conflictFree = false; }
    }
  }
}
check('assignment is conflict-free (no gap)', conflictFree, true);

// With minGapBeats 0.5 at 10 players
const a10gap = assignPlayers(events, 10, { division, minGapBeats: 0.5, handsPerPlayer: 1 });
const conflict05 = buildConflictGraph(events, Math.round(0.5 * division));
let conflictFree05 = true;
for (const bells of a10gap.players) {
  for (let i = 0; i < bells.length; i++) {
    for (let j = i + 1; j < bells.length; j++) {
      if (conflict05[bells[i]]?.has(bells[j])) { conflictFree05 = false; }
    }
  }
}
check('assignment conflict-free with 0.5-beat gap', conflictFree05, true);
check('minGapBeats stored on assignment', a10gap.minGapBeats, 0.5);

// Regression baselines at 10 players, seed=0
check('pitchCost baseline (10 players)', a10.pitchCost, 12);
check('spread baseline (10 players)', a10.spread, 19);

// Pins honored
const a10pin = assignPlayers(events, 10, { division, pins: { 'C4': 0, 'G4': 9 }, handsPerPlayer: 1 });
check('pin C4 -> player 0', a10pin.players[0].includes('C4'), true);
check('pin G4 -> player 9', a10pin.players[9].includes('G4'), true);

// minCount honored
const a10min = assignPlayers(events, 10, { division, minCount: 15, handsPerPlayer: 1 });
const allAboveFloor = a10min.playerSums.every(s => s >= 15);
check('all players >= minCount=15', allAboveFloor, true);

// Friendly errors
function expectError(label, fn, substr) {
  try { fn(); check(`${label} — should throw`, false, true); }
  catch (e) { check(`${label} — throws: "${e.message.slice(0, 50)}"`, e.message.includes(substr), true); }
}
expectError('too many players', () => assignPlayers(events, 99, { division }), 'only');
expectError('negative minGapBeats', () => assignPlayers(events, 10, { division, minGapBeats: -1 }), "negative");
expectError('infeasible minCount', () => assignPlayers(events, 10, { division, minCount: 9999 }), 'only');

// ── Two-hand ringing property checks ─────────────────────────────────────────
// Default handsPerPlayer is 2 — every player's bells only need to be splittable
// into two conflict-free hands (the induced conflict subgraph must be bipartite).
const a10two = assignPlayers(events, 10, { division, handsPerPlayer: 2 });
const assignedBellsTwo = a10two.players.flat().sort();
check('two-hand: all bells assigned exactly once', assignedBellsTwo, allBells);

let twoHandBipartite = true;
for (const bells of a10two.players) {
  for (let i = 0; i < bells.length; i++) {
    for (let j = i + 1; j < bells.length; j++) {
      const b1 = bells[i], b2 = bells[j];
      if (conflict[b1]?.has(b2) && a10two.hands[b1] === a10two.hands[b2]) twoHandBipartite = false;
    }
  }
}
check("two-hand: every player's bells are 2-colorable (no same-hand conflict edge)", twoHandBipartite, true);

// Two-hand should never do worse than strict single-hand: find a min-gap that
// forces conflicts in strict mode, then confirm two-hand mode clears them (or
// strictly reduces the number of flagged same-hand conflicts).
function countFlaggedConflicts(a) {
  let n = 0;
  for (const bells of a.players) {
    for (let i = 0; i < bells.length; i++) {
      for (let j = i + 1; j < bells.length; j++) {
        if (a.conflicts[bells[i]]?.includes(bells[j]) && a.hands[bells[i]] === a.hands[bells[j]]) n++;
      }
    }
  }
  return n;
}

let strictGapBeats = null;
for (const gap of [1, 1.5, 2, 2.5, 3, 4, 5, 6, 8]) {
  if (assignPlayers(events, 10, { division, minGapBeats: gap, handsPerPlayer: 1 }).hasConflicts) {
    strictGapBeats = gap;
    break;
  }
}
if (strictGapBeats !== null) {
  const strict = assignPlayers(events, 10, { division, minGapBeats: strictGapBeats, handsPerPlayer: 1 });
  const twoHandVariant = assignPlayers(events, 10, { division, minGapBeats: strictGapBeats, handsPerPlayer: 2 });
  const improved = twoHandVariant.hasConflicts === false
    || countFlaggedConflicts(twoHandVariant) < countFlaggedConflicts(strict);
  check(`two-hand is never worse than single-hand (gap=${strictGapBeats} beats forces strict-mode conflicts)`, improved, true);
} else {
  check('two-hand is never worse than single-hand (no gap found that forces strict-mode conflicts)', true, true);
}

// ── "Bells used" header strip ───────────────────────────────────────────────
// name → MuseScore pitch/tpc conversion (must match the parser's tpcToName).
check('nameToPitchTpc C4', nameToPitchTpc('C4'), { midi: 60, tpc: 14 });
check('nameToPitchTpc F#5', nameToPitchTpc('F#5'), { midi: 78, tpc: 20 });
check('nameToPitchTpc Bb3', nameToPitchTpc('Bb3'), { midi: 58, tpc: 12 });

// The generated strip score round-trips through the parser: same bells, same
// order, colors preserved on every note.
const stripNames = ['C4', 'E4', 'F#4', 'G4', 'C5'];
const stripColors = new Map(stripNames.map((n, i) => [n, [i * 10, 50, 200]]));
const stripMscz = buildBellsUsedScore(stripNames, stripColors);
const stripEvents = parseNotes(stripMscz);
check('strip: one note per bell', stripEvents.length, stripNames.length);
check('strip: bells in ascending order', stripEvents.map(e => e.name), stripNames);
const stripXml = new TextDecoder().decode(
  (await import('fflate')).unzipSync(stripMscz)['score.mscx'],
);
check('strip: every note is colored', (stripXml.match(/<color /g) || []).length, stripNames.length);
check('strip: noteheads are stemless', (stripXml.match(/<noStem>1<\/noStem>/g) || []).length, stripNames.length);

console.log(`\n${pass} passed, ${fail} failed`);
if (fail > 0) process.exit(1);
